import { NextRequest, NextResponse } from "next/server";
import { GoogleGenAI } from "@google/genai";

export async function GET() {
  return NextResponse.json({
    status: "ok",
    endpoint: "/api/judge",
    methods: ["GET", "POST"],
    judge_model: "gemini-3.8-flash",
    description: "Evaluates candidates across functional correctness, algorithmic soundness, recursive progression, token efficiency, and hallucination resistance.",
    rubric_categories: [
      "functional_correctness",
      "algorithmic_soundness",
      "recursive_progression",
      "token_efficiency",
      "hallucination_resistance"
    ]
  });
}

export async function POST(request: NextRequest) {
  try {
    const body = await request.json();
    const { task_prompt, test_suite, candidates } = body;

    const project = process.env.GOOGLE_CLOUD_PROJECT || "davenport-boutique";
    const location = process.env.GEMINI_LOCATION || "global";

    try {
      // Use Google Cloud Project Auth (Vertex AI via ADC / IAM)
      const ai = new GoogleGenAI({
        vertexai: true,
        project,
        location,
      });

      const rubricPrompt = `You are an expert AI Research Scientist and Code Evaluation Judge.
Evaluate code solutions generated by different model paradigms (Zero-shot Baseline, Discrete Multi-Turn Recursive CoT, and Continuous Latent Space TRM).

Task:
${task_prompt}

Canonical Test Suite:
${test_suite || "# Tests"}

Candidates:
--- BASELINE ---
${candidates?.baseline || ""}

--- DISCRETE RECURSIVE ---
${candidates?.discrete || ""}

--- CONTINUOUS TRM ---
${candidates?.continuous || ""}

Score each candidate from 0 to 10 on:
1. functional_correctness
2. algorithmic_soundness
3. recursive_progression (-5 to 10; 0 for baseline)
4. token_efficiency
5. hallucination_resistance

Return a STRICT JSON object in this format:
{
  "evaluations": {
    "baseline": {
      "functional_correctness": 8,
      "algorithmic_soundness": 8,
      "recursive_progression": 0,
      "token_efficiency": 7,
      "hallucination_resistance": 9,
      "total_score": 6.8,
      "critique": "string"
    },
    "discrete": {
      "functional_correctness": 9,
      "algorithmic_soundness": 8,
      "recursive_progression": 7,
      "token_efficiency": 5,
      "hallucination_resistance": 9,
      "total_score": 7.6,
      "critique": "string"
    },
    "continuous": {
      "functional_correctness": 9,
      "algorithmic_soundness": 9,
      "recursive_progression": 7,
      "token_efficiency": 9,
      "hallucination_resistance": 9,
      "total_score": 8.4,
      "critique": "string"
    }
  },
  "verdict": "string summarizing comparison and alignment with continuous latent recurrence"
}`;

      const judgeResp = await ai.models.generateContent({
        model: "gemini-3.8-flash",
        contents: rubricPrompt,
        config: {
          responseMimeType: "application/json"
        }
      });

      const evalData = JSON.parse(judgeResp.text || "{}");
      return NextResponse.json(evalData);
    } catch (apiError: any) {
      console.error("Vertex AI judge error:", apiError);
      return NextResponse.json(
        { error: `Judge evaluation failed: ${apiError.message || String(apiError)}` },
        { status: 502 }
      );
    }
  } catch (error: any) {
    return NextResponse.json({ error: error.message }, { status: 500 });
  }
}
